version: '2'
services:
  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dilectic

  weyl:
    image: quartic/weyl
    ports:
      - "8080:8080"
    volumes:
      - ./weyl.yml:/weyl-service/weyl.yml
    depends_on:
      - "postgis"
