---
type: "geojson"
name: "National Grid Cables"
description: "National Grid Cables Infrastructure"
attribution: "National Grid"
icon: "random"
path: "/datasets/Cable.geojson"
map:
  titleAttribute: "CABLE_ROUT"
