---
type: "geojson"
name: "National Grid Towers"
description: "National Grid Tower Infrastructure"
attribution: "National Grid"
icon: "plug"
path: "/datasets/Towers.geojson"
map:
  titleAttribute: "TOWER_ASSE"
