---
type: "postgres"
name: "Residential Buildings"
description: "Residential buildings"
query: "SELECT * FROM planet_osm_polygon where building IN
  ('house', 'country_house', 'palace', 'apartments', 'semidetached_house',
  'houses', 'flats', 'tower_block', 'terrace_house', 'residential', 'tower',
  'block', 'hall_of_residence', 'yes;house','council_flats')"
