version: '2'
services:
  postgis-1:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dilectic
