version: '2'
services:
  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dilectic

  catalogue:
    image: eu.gcr.io/quartic-oliver/catalogue:${PLATFORM_VERSION}
    ports:
      - "8090:8090"
    volumes:
      - ./catalogue/catalogue.yml:/catalogue-service/catalogue.yml
    environment:
      - CATALOGUE_SERVICE_OPTS=-Xms64m -Xmx64m

  weyl:
    image: eu.gcr.io/quartic-oliver/weyl:${PLATFORM_VERSION}
    ports:
      - "8080:8080"
    volumes:
      - ./weyl/weyl.yml:/weyl-service/weyl.yml
    environment:
      - WEYL_SERVICE_OPTS=-Xms32g -Xmx32g
    links:
      - postgis
      - catalogue

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - weyl
