---
tag: "large"
type: "postgres"
name: "Postcode Districts"
description: "Postcode districts in the UK"
query: "SELECT * from postcode_districts"
map:
  titleAttribute: "name"
  blessedAttributes:
    - "gid"
