---
tag: "small"
type: "geojson"
name: "Outdoor Advertising Stock London"
description: "Digital billboards, panels and signs in London"
path: "/datasets/signkick.geojson"
map:
  titleAttribute: "Name"
  blessedAttributes:
    - "Price"
    - "Is Digital"
  imageAttribute: "street_view"
