---
type: "websocket"
name: "Mock Tracking"
description: "Mock GPS Location Tracking"
attribution: "Quartic"
icon: "location arrow"
context_path: "/mock-tracker"
map:
  viewType: "LOCATION_AND_TRACK"
