---
type: "websocket"
name: "National Grid Instantaneous Flows"
description: "Real time (2mins) National Grid Instantaneous Gas Flows"
attribution: "National Grid"
icon: "sitemap"
context_path: "/national-grid"
