---
type: "websocket"
name: "Quartic Tracking"
description: "Quartic GPS Location Tracking"
attribution: "Quartic"
icon: "location arrow"
context_path: "/tracker"
map:
  viewType: "LOCATION_AND_TRACK"
